In [55]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

In [56]:
DATADIR = "/Users/neharajendrabaritamboli/Desktop/HR/training"

In [57]:
DATADIR

'/Users/neharajendrabaritamboli/Desktop/HR/training'

In [58]:
CATEGORIES = ["Alef", "Ayin", "Bet", "Dalet", "Gimel", "He", "Het", "Kaf", "Kaf-final", "Lamed", "Mem", "Mem-medial", "Nun-final", "Nun-Medial", "Pe", "Pe-final", "Qof", "Resh", "Samekh", "Shin", "Taw", "Tet", "Tsadi-final", "Tsadi-medial", "Waw", "Yod", "Zayin"]
# category type list.

In [59]:
CATEGORIES

['Alef',
 'Ayin',
 'Bet',
 'Dalet',
 'Gimel',
 'He',
 'Het',
 'Kaf',
 'Kaf-final',
 'Lamed',
 'Mem',
 'Mem-medial',
 'Nun-final',
 'Nun-Medial',
 'Pe',
 'Pe-final',
 'Qof',
 'Resh',
 'Samekh',
 'Shin',
 'Taw',
 'Tet',
 'Tsadi-final',
 'Tsadi-medial',
 'Waw',
 'Yod',
 'Zayin']

In [60]:
for category in CATEGORIES:  
    path = os.path.join(DATADIR,category)  
    for img in os.listdir(path): 
        img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
        #plt.imshow(img_array, cmap='gray')  
        #plt.show()  # display!

        #break 
    #break 


In [61]:
IMG_SIZE = 28

In [62]:
def create_training_data():
    training_data = []
    for category in CATEGORIES:  

        path = os.path.join(DATADIR,category)  
        class_num = CATEGORIES.index(category)  # get the classification  (0 to 26).

        for img in tqdm(os.listdir(path)):  # iterate over each image per category
            
            try:
                
                img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                training_data.append([new_array, class_num])  # add this to our training_data
                
            except Exception as e:  # in the interest in keeping the output clean...
                pass
            except OSError as e:
                print("OSErrroBad img most likely", e, os.path.join(path,img))
            except Exception as e:
                print("general exception", e, os.path.join(path,img))
    return training_data





In [63]:
training_data = create_training_data()

100%|██████████| 12/12 [00:00<00:00, 3701.67it/s]


In [64]:
len(training_data)

5537

In [65]:
type(training_data)

list

In [66]:
sample_labels = np.zeros(len(training_data))
for index,sample in enumerate(training_data):
    sample_labels[index] = sample[1]
    
    

In [67]:
np.arange(27)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [68]:
# verifying if the data is loaded or not. All the data is loaded and the last array in the
# tuple has 12 samples which is right.
for ii in np.arange(27):
    itemindex = np.where(sample_labels==ii)

    print("label is %s"%ii)
    print("number of samples is %s"%(len(itemindex[0])))
    

label is 0
number of samples is 300
label is 1
number of samples is 300
label is 2
number of samples is 300
label is 3
number of samples is 91
label is 4
number of samples is 300
label is 5
number of samples is 300
label is 6
number of samples is 300
label is 7
number of samples is 193
label is 8
number of samples is 10
label is 9
number of samples is 294
label is 10
number of samples is 300
label is 11
number of samples is 300
label is 12
number of samples is 130
label is 13
number of samples is 300
label is 14
number of samples is 37
label is 15
number of samples is 15
label is 16
number of samples is 265
label is 17
number of samples is 78
label is 18
number of samples is 300
label is 19
number of samples is 300
label is 20
number of samples is 300
label is 21
number of samples is 300
label is 22
number of samples is 73
label is 23
number of samples is 300
label is 24
number of samples is 116
label is 25
number of samples is 23
label is 26
number of samples is 12


In [70]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))

X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

[[[[254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]
   [254]]

  [[255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [158]
   [100]
   [100]
   [100]
   [135]
   [242]
   [255]
   [255]
   [255]
   [255]]

  [[255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [173]
   [ 14]
   [  0]
   [  0]
   [  0]
   [  0]
   [ 72]
   [239]
   [255]
   [255]
   [255]]

  [[255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [255]
   [154]
   [ 64]
   [ 64]
   [ 64]
   [ 64]
   [ 97]
   [216]
   [255]
   [255]
   [159]
   [  0]
   [  0]
   [  0]
   [  0]
   [  0]
   [  0]
   [  8]
   [135]
   [

In [72]:
import pickle

pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [73]:
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

In [75]:
X

array([[[[254],
         [254],
         [254],
         ...,
         [254],
         [254],
         [254]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        ...,

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]]],


       [[[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [255],
         [255],
         [255]],

        [[255],
         [255],
         [255],
         ...,
         [118],
         [

In [80]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

import pickle

pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

X = X/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('softmax'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, y, batch_size=44, epochs=5, validation_split=0.6)

Train on 2214 samples, validate on 3323 samples
Epoch 1/5
2214/2214 [==============================] - 36s 16ms/step - loss: -42.9883 - acc: 0.1355 - val_loss: -248.9420 - val_acc: 0.0000e+00
Epoch 2/5
2214/2214 [==============================] - 43s 19ms/step - loss: -42.9883 - acc: 0.1355 - val_loss: -248.9420 - val_acc: 0.0000e+00
Epoch 3/5
2214/2214 [==============================] - 45s 20ms/step - loss: -42.9883 - acc: 0.1355 - val_loss: -248.9420 - val_acc: 0.0000e+00
Epoch 4/5
2214/2214 [==============================] - 35s 16ms/step - loss: -42.9883 - acc: 0.1355 - val_loss: -248.9420 - val_acc: 0.0000e+00
Epoch 5/5
2214/2214 [==============================] - 37s 16ms/step - loss: -42.9883 - acc: 0.1355 - val_loss: -248.9420 - val_acc: 0.0000e+00


In [ ]:
# pathetic model
